// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPortfolio.Data;

#nullable disable

namespace MyPortfolio.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20251028101539_CreatingTblContact")]
    partial class CreatingTblContact
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyPortfolio.Models.EntityModels.TblContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNO")
                        .IsRequired()
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("Varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TblContacts");
                });

            modelBuilder.Entity("MyPortfolio.Models.EntityModels.TblLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TblLogins");
                });

            modelBuilder.Entity("MyPortfolio.Models.EntityModels.TblPersonal_Project_Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("Varchar(500)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TblPersonal_Project_Details");
                });

            modelBuilder.Entity("MyPortfolio.Models.EntityModels.TblServices_Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("Varchar(500)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<byte[]>("img")
                        .IsRequired()
                        .HasColumnType("Varbinary(MAX)");

                    b.HasKey("Id");

                    b.ToTable("TblServices_Details");
                });
#pragma warning restore 612, 618
        }
    }
}
